### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by rbhatt1999** [XRichardroidX/JS-Capstone#44]
# Good job so far 🥇 

## You've done a great job till now. I have few suggestion for you to improve the user experience of your websites below:

1- You can add production mode for the build script since both are running in development mode only. 
https://github.com/XRichardroidX/JS-Capstone/blob/af78c01c9efa5f3cf72db7532a3f384be2835e6b/package.json#L8-L9

2- Make a summary excerpt on the home page to the full summary in the popup.
![image](https://user-images.githubusercontent.com/112093825/210723692-f9a56ded-c009-46d0-af24-c84c82e67feb.png)

3- Add title for your website.

4- [Optional] add favicon for your website.

**Comment by XRichardroidX** [comment]
Thank you for the review, changes has been made to that, I really appreciate the effort and time.
